export const DEFAULT_MIN_CREDIBILITY = 0.8;
export const DEFAULT_MIN_ISSUE_CREDIBILITY = 0.8;
export const DEFAULT_EXCESSIVE_PR_PENALTY_THRESHOLD = 2;
export const DEFAULT_OPEN_ISSUE_SPAM_THRESHOLD = 2;
